### ISSUE TITLE
Consider hiding about:newtab footer

### ISSUE THREAD

**Issue by elerch** [overdodactyl/userContent-tweaks#16]
This might be beyond the scope of the project, but in my own tweaks I had a rule:

```css
@-moz-document url(about:newtab) {
  /* Turn off new user guidance */
  footer {display:none;}
}
```

I'd like to submit this rule for consideration of inclusion into the project. On one hand it goes beyond the scope of styling the existing pages. However, I feel anyone who installs Firefox and goes through the necessary steps to install this project clearly doesn't need those little hint snippets Firefox gives new users on the new tab page. 

Also this rule might not be specific enough - I just kind of slapped it into my .css so I never had to see those hints again. ;)

**Comment by overdodactyl** [comment]
Hi @elerch!

I think you're right - anyone using this repo probably doesn't need or want that message haha.  

Maybe increase the specificity and expand it to `about:home` as well? I don't use either of those pages, so I'm not really sure if the footer is utilized for any other purpose. 

```css
@-moz-document url(about:newtab), url(about:home) {
    #onboarding-notification-bar.onboarding-opened {
        display: none !important;
    }
}
```
