### ISSUE TITLE
in-content styling

### ISSUE THREAD

**Issue by hensm** [overdodactyl/userContent-tweaks#2]
It's possible to do most of the in-content dark theme by just changing the existing variables.

```css
:root {
	--in-content-page-color: #0c0c0d;
	--in-content-page-background: #f9f9fa;
	--in-content-text-color: #0c0c0d;
	--in-content-selected-text: #fff;
	--in-content-box-background: #fff;
	--in-content-box-background-odd: #f3f6fa;
	--in-content-box-background-hover: #ebebeb;
	--in-content-box-background-active: #dadada;
       /* ... */
}
```

All the widget styling can be shared between pages, too. I think it affects most of the about: pages, so this is a super-easy way to do most of the work in one go.
